CORTX-29121 readme rgw updates
Seagate/cortx-k8s pull request #133
Opened 2022-03-02 20:04 UTC by osowski

Update root README.md to include changes specific to RGW component integration, as well as updated formatting for future ease of authoring.

2022-03-02 20:10 UTC, walterlopatka approved these changes
lgtm

2022-03-03 00:47 UTC, keithpine requested changes

2022-03-03 00:47 UTC, keithpine commented on README.md
> +| `common.hax.procotol`                                 | Protocol that is used to communicate with HAX components running across Server and Data Pods.     | `https` |
```suggestion
| `common.hax.protocol`                                 | Protocol that is used to communicate with HAX components running across Server and Data Pods.     | `https` | 
```

2022-03-03 00:47 UTC, keithpine commented on README.md
> +| `namespace`              | The kubernetes namespace for CORTX Pods to be deployed in.                              | `default`               |
```suggestion
| `namespace`              | The Kubernetes namespace for CORTX Pods to be deployed in.                              | `default`               |
```

2022-03-03 15:56 UTC, keithpine approved these changes

2022-03-03 15:58 UTC, walterlopatka approved these changes

2022-03-03 16:14 UTC, merged