CORTX-28904:changed rgw external ports to 80 & 443
Seagate/cortx-k8s pull request #137
Opened 2022-03-03 13:51 UTC by lakshita-jain

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

2022-03-03 14:03 UTC, ujjwalpl approved these changes

2022-03-04 04:11 UTC, tanujashinde0405 requested changes

2022-03-04 04:11 UTC, tanujashinde0405 commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
> +      targetPort: 80
change this to 22751

2022-03-04 04:11 UTC, tanujashinde0405 commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
> +      targetPort: 443
change this to 23001

2022-03-04 04:11 UTC, tanujashinde0405 commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
>        port: 80
change this to 22751

2022-03-04 04:11 UTC, tanujashinde0405 commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-server/templates/cortx-server-svc.yaml
>        port: 443
change this to 23001

2022-03-04 07:15 UTC, nitin-seagate approved these changes
LGTM

2022-03-04 08:47 UTC, lakshita-jain commented on k8_cortx_cloud/cortx-cloud-helm-pkg/cortx-platform/templates/cortx-io-svc.yaml
> +      targetPort: 443
changes done in the new commit

2022-03-04 08:47 UTC, tanujashinde0405 approved these changes

2022-03-04 08:47 UTC, merged