UDX-6642: Fix for Support Bundle tarfiles are not included in final t…
Seagate/cortx-k8s pull request #15
Opened 2021-11-22 08:37 UTC by gargpalak048

Include generated SB tarfiles in the final output tarball generated by log collector script

2021-11-22 08:38 UTC, gargpalak048 commented on k8_cortx_cloud/logs-cortx-cloud.sh
> +  tar rf $logs_folder.tar ./${logs_folder}
Added #L61 as a fix.
@cdeshmukh

2021-11-22 09:02 UTC, cdeshmukh requested changes

2021-11-22 09:22 UTC, gargpalak048 commented on k8_cortx_cloud/logs-cortx-cloud.sh
> +  tar rf $logs_folder.tar ./${logs_folder}
${logs_folder} will contain the SB tarfiles, we are adding it to the tar in a similar way saveLogs() & savePodDeatils() is adding to it.

Please refer to #L38 & #L50

2021-11-23 07:32 UTC, gargpalak048 commented on k8_cortx_cloud/logs-cortx-cloud.sh
> +  tar rf $logs_folder.tar ./${logs_folder}
Also, changed the output file from tar to tar.gz compressed file

2022-01-18 18:37 UTC, closed without merging