Rename `solution.yaml` to `solution.example.yaml`.
Seagate/cortx-k8s pull request #164
Opened 2022-03-14 19:37 UTC by keithpine

This serves a few purposes:

- Less chance of accidental modifications to the source controlled example
- Avoids accidental use of the wrong file (default as `solution.yaml`) when using files with different names
- Makes it obvious that the default file is just an example that should be customized

Signed-off-by: Keith Pine <keith.pine@seagate.com>

2022-03-14 19:38 UTC, keithpine commented
Could potentially have some impact on CI jobs if they rely on this file.

2022-03-14 19:55 UTC, walterlopatka approved these changes
lgtm

2022-03-15 16:59 UTC, keithpine commented
@shailesh-vaidya FYI, for Jenkins updates.

2022-03-16 01:14 UTC, osowski requested changes
In the spirit of tolerant changes, let's make this a progressive change instead of an abrupt breaking change.

Can we add the new solution.yaml.example file, comment and deprecate the current solution.yaml file, cut a release, make sure processes get updated, then remove the current solution.yaml file in the next release instead.

That should give @shailesh-vaidya and the cortx-re team enough time to adopt changes instead of breaking anything in the interim.

2022-03-23 00:54 UTC, osowski approved these changes
lgtm

2022-03-23 02:48 UTC, walterlopatka approved these changes

2022-03-23 02:49 UTC, merged