[WIP] CORTX-29590: Seamless rolling upgrade framework to address temporary …
Seagate/cortx-k8s pull request #182
Opened 2022-03-28 06:30 UTC by tanujashinde0405

…fix for pod delete/restart issue

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

2022-03-28 06:35 UTC, ujjwalpl requested changes

2022-03-28 06:35 UTC, ujjwalpl commented on k8_cortx_cloud/upgrade-cortx-cloud.sh
> +function silentKill()
Please following coding conventions. Code follows xxx_yyy() convention.

2022-03-28 06:52 UTC, tanujashinde0405 commented on k8_cortx_cloud/upgrade-cortx-cloud.sh
> +function silentKill()
done

2022-03-29 08:15 UTC, ujjwalpl requested changes

2022-03-29 08:15 UTC, ujjwalpl commented on k8_cortx_cloud/upgrade-cortx-cloud.sh
> +if ! wait_for_all_deployments_available 300s "CORTX PODs" "${cortx_deployments[@]}"; then
Please change the name to generic one i.e. "wait_for_all_pods_available", so that we mimnmize the rework when we switch to statefulsets.

2022-03-29 08:47 UTC, ujjwalpl approved these changes

2022-03-29 14:21 UTC, nitin-seagate approved these changes
LGTM... Fix codacy issues

2022-03-30 04:12 UTC, merged