CORTX-30141: Remove CORTX secrets custom template file
Seagate/cortx-k8s pull request #232
Opened 2022-05-04 19:48 UTC by keithpine

## Description
Remove the custom template file used for creating the CORTX secret, and generate the secret directly with `kubectl create`. This reduces the number of template files to manage, in support of merging the cortx-configmap Chart into the "unified" Chart.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [ ] Documentation additions or improvements
- [X] Code quality improvements to existing code or test additions/updates

## Applicable issues

- This change is related to an issue: CORTX-30141

## How was this tested?

## Additional information
Deployed a cluster and performed S3 I/O for each of these:

- custom passwords in solution.yaml
- auto-generated passwords
- an external secret

Examined the created secret and compared it from previous, no unexpected changes seen.

## Checklist

- [X] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [X] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change addresses a CORTX Jira issue:

- [X] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

2022-05-04 19:55 UTC, walterlopatka approved these changes
lgtm

2022-05-06 21:30 UTC, osowski requested changes

2022-05-06 22:36 UTC, keithpine commented on k8_cortx_cloud/deploy-cortx-cloud.sh
> +        if ! kubectl create secret generic "${cortx_secret_name}" \
It doesn't look like this command exists:

```sh
❯ kubectl apply secret -f /tmp/foo.yaml 
error: Unexpected args: [secret]
See 'kubectl apply -h' for help and examples
```

If we want to use `apply`, then I can just close this PR and move the bespoke template file to another location. I was mostly just attempting to get rid of it.

2022-05-07 01:07 UTC, osowski approved these changes

2022-05-07 01:07 UTC, merged