CORTX-30966: Support SSL Certificate as a Secret
Seagate/cortx-k8s pull request #360
Opened 2022-08-27 00:28 UTC by walterlopatka

## Description

This change updates the deploy support for the SSL certficate that is used for cortx-control (CSM) and cortx-server (RGW) pods.

In solution.yaml, if common.ssl.secret is specified, then a pre-built SSL certifiate will be used to create the Secret that holds the certificate.

Alternatively, if common.ssl.externa_secret is specified, then CORTX will use the certificate contained in the specified
secret.

The specified secret must be in the form of a pem file that contains both the certifcate and private key.

Note: It would be better to generate a certificate rather than use a previously-generated one.  This PR does not address this, but rather continues the current process of using the previously-generated certificate.  We can work on that later.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds new functionality)
- [ ] Breaking change (bug fix or new feature that breaks existing functionality)
- [ ] Third-party dependency update
- [ ] Documentation additions or improvements
- [ ] Code quality improvements to existing code or test additions/updates

## Applicable issues

- This change fixes an issue: CORTX-30966

## CORTX image version requirements
N/A

## How was this tested?
- For each of the following scenarios I deployed, created an IAM use (CSM), ran S3 IO, and destroyed the cluster
  - deploy script creates secret:
    - default config: "cortx-cert", "cortx.pem"
    - alternate secret name
    - alternate secret key
  - use external secret
- Tested solution.yaml validation

## Checklist

- [x] The change is tested and works locally.
- [ ] New or changed settings in the solution YAML are documented clearly in the README.md file.
- [x] All commits are signed off and are in agreement with the [CORTX Community DCO and CLA policy](https://github.com/Seagate/cortx/blob/main/doc/dco_cla.md).

If this change requires newer CORTX or third party image versions:

- [ ] The `image` fields in [solution.example.yaml](../k8_cortx_cloud/solution.example.yaml) have been updated to use the required versions.
- [ ] The `appVersion` field of the [Helm chart](../charts/cortx/Chart.yaml) has been updated to use the new CORTX version.

If this change addresses a CORTX Jira issue:

- [x] The title of the PR starts with the issue ID (e.g. `CORTX-XXXXX:`)

2022-08-27 00:29 UTC, walterlopatka commented
I still need to update the documentation.

2022-08-27 16:22 UTC, walterlopatka commented on charts/cortx/templates/_config.yaml.tpl
> -      ssl_certificate: /etc/cortx/solution/ssl/s3.seagate.com.pem
This name could be anything.  "s3.seagate.com.pem" didn't seem right, so I changed it to a simple "cortx.pem".

2022-08-29 21:51 UTC, osowski reviewed
Overall it looks good. Just a question on the parameters getting added. I would expect it to be the case of:
`common.ssl.secret` || (`common.ssl.external_secret` && `common.ssl.secret_key`)

I don't think it makes sense from a user experience to require the user the specify what the name of the key is inside of the Secret we are going to generate. It would make more sense for us to just pick one we'd prefer to use already.

@keithpine thoughts?

2022-08-29 22:55 UTC, keithpine requested changes
I'd prefer to see the Secret continue to be managed by Helm. If that's not feasible, let me know.

2022-08-29 22:55 UTC, keithpine commented on k8_cortx_cloud/deploy-cortx-cloud.sh
> +        fi
Don't need this if using a Helm-managed secret.

2022-08-29 22:55 UTC, keithpine commented on README.md
> +| `common.ssl.secret`                                   | Name of a Secret to be generated by `deploy-cortx-cloud.sh` that contains a self-signed certificate.<br />Note: Either `common.ssl.secret` or
I don't think this option is necessary. Why don't we just use the name we already do, which is derived from the release ({release name}-ssl-cert)?

2022-08-29 22:55 UTC, keithpine commented on README.md
> +| `common.ssl.external_secret`                          | Names of an existing Secret that contains a TLS/SSL certificate.  This certificate must be in PEM format and must contain the Private Key and
```suggestion
| `common.ssl.external_secret`                          | Name of an existing Secret that contains a TLS/SSL certificate. The certificate is a single file in PEM form that includes the full certificate chain and private key in PEM format. If the external secret is not provided, a self-signed certificate will be used instead. | `""` |
```

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/templates/_config.yaml.tpl
>        device_certificate: /etc/cortx/solution/ssl/stx.pem
Unrelated, but are these necessary?

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/templates/control/deployment.yaml
> +            secretName: {{ .Values.control.certificateSecret }}
Instead, rename template `cortx.tls.configmapName` to `cortx.tls.secretName`, and derive it based on either the release name, or use the externally provided name.

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/README.md
> +| server.certificateSecretKey | string | `""` | Name of Secret key that contains the certificate |
Is it really necessary to provide this flexibility?

Say one day we can upgrade to using a real tlsSecret, those fields are fixed anyways. Why not just require a fixed key name, and just document that.

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/values.yaml
> +  certificateSecret: ""
Remove in favor of using auto-generated secret name.

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/values.yaml
> +  certificateSecret: ""
Remove in favor of using auto-generated secret name.

2022-08-29 22:55 UTC, keithpine commented on charts/cortx/values.yaml
> +  certificateSecretKey: ""
I like the idea of being able to specify these separately, but I don't think CORTX allows this? The cluster configuration only provides a single certificate value for all components. What would happen if you actually used two different secrets?

I think this has to be a single value at the top-level.

2022-08-29 22:55 UTC, keithpine commented on k8_cortx_cloud/deploy-cortx-cloud.sh
> +
Don't need this if using a Helm-managed secret.

2022-08-29 22:55 UTC, keithpine commented on k8_cortx_cloud/destroy-cortx-cloud.sh
> +    fi
Don't need this if using a Helm-managed secret.

2022-08-29 22:55 UTC, keithpine commented on k8_cortx_cloud/solution.example.yaml
> +       secret_key: cortx.pem
Don't need this if using a Helm-managed secret.

2022-08-29 22:55 UTC, keithpine commented on k8_cortx_cloud/solution_validation_scripts/solution-check.yaml
> +      secret_key: required
Don't need this if using a Helm-managed secret.

2022-08-30 19:57 UTC, walterlopatka commented
Closing at this PR is hopeless.  I have resubmitted #362

2022-08-30 19:57 UTC, closed without merging