Include generate cortx-all container image in the documentation
Seagate/cortx-k8s pull request #48
Opened 2022-01-13 12:48 UTC by r-wambui

- Add instructions where users can also generate their own cortx-all image instead of using the image hosted on ghcr.io

2022-01-13 19:45 UTC, johnbent approved these changes
LGTM. @gregnsk ?

2022-01-14 00:21 UTC, johnbent requested changes

2022-01-14 00:21 UTC, johnbent commented on doc/cortx-aws-k8s-installation.md
> +1.  To use container images hosted on the [repostitory](https://github.com/Seagate/cortx/pkgs/container/cortx-all)
Repository is spelled wrong here. Please fix.

2022-01-14 18:21 UTC, osowski approved these changes
lgtm

2022-01-14 18:21 UTC, merged