Add Github Action for shellcheck
Seagate/cortx-k8s pull request #58
Opened 2022-01-22 00:26 UTC by keithpine

Lint all bash scripts using [shellcheck](https://github.com/koalaman/shellcheck) for any push to main or integration branches and PRs.

Some extra strict options are enabled in .shellcheckrc (v0.8.0 required). All of the enabled checks cover some aspects of several Bash style guides, although they aren't all identical:

  - [bahamas10/bash-style-guide](https://github.com/bahamas10/bash-style-guide)
  - [BashGuide/Practices](http://mywiki.wooledge.org/BashGuide/Practices)
  - [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html)

For now, the Action is configured to always succeed because of existing failures.

Signed-off-by: Keith Pine <keith.pine@seagate.com>

2022-01-22 00:37 UTC, walterlopatka commented
LGTM (though I admit I don't have experience with this)

2022-01-22 00:40 UTC, walterlopatka approved these changes

2022-01-22 02:31 UTC, johnbent commented
@keithpine and @walterlopatka , I think this might be redundant since Codacy is already attached to this repo.

Here is a picture showing the Codacy badge attached to the front README of this repo.
![image](https://user-images.githubusercontent.com/2047294/150621485-66fb0650-0721-4d8e-8656-8df33af1a145.png)
If you click on the badge, it will bring you to the Codacy dashboard for this repo. 

You'll also notice that Codacy is already doing checks on each pull request:
![image](https://user-images.githubusercontent.com/2047294/150621515-34efb73f-c745-4fbe-91c8-a4a8b15dad96.png)

And, finally, this page suggests to me that Codacy includes shellcheck:
https://docs.codacy.com/related-tools/codacy-plugin-tools/

2022-01-22 02:34 UTC, johnbent commented
Confirmed. I logged in to Codacy and looked at settings for the k8s repo and here is what I see:

![image](https://user-images.githubusercontent.com/2047294/150621624-8925895a-7744-447e-b6a6-c6f1d8a9cf78.png)

2022-01-24 18:16 UTC, keithpine commented
@johnbent Thanks for that info. A couple of questions:

1. The version of Shellcheck being used is quite old, can it be upgraded? There are a couple of style checks that I've enabled that are not supported in the Codacy version.
2. Looks like the Codacy run is not flagging the same number of issues, the issue counts are significantly less than what the manual run sees. Can we enable all of the checks (and reduce if needed)? Do you know how the config file setting works? Will it select the `.shellcheckrc` file if it's in the repository, that way it could be managed w/o access to the Codacy admin panel.
3. How do we get Codacy to fail the PR check if it detects these issues in the future?

2022-01-24 19:10 UTC, johnbent commented
Plus @mukul-seagate11 . Mukul, can you help answer Keith's questions above about Codacy?

2022-01-31 20:51 UTC, osowski requested changes
I'm good with this as a practice. I understand Codacy may run some of this, but I would prefer to control it with a finer-grained approach and then remove it when we have minimal (if any) shell scripts in the future.

The only change I would request is that we need to fork https://github.com/ludeeus/action-shellcheck in a github.com/Seagate repository and reference it in the `uses` path that way, instead of directly referencing the remote repository to run code in our pipeline unsupervised.

2022-02-01 04:48 UTC, mukul-seagate11 commented
> I'm good with this as a practice. I understand Codacy may run some of this, but I would prefer to control it with a finer-grained approach and then remove it when we have minimal (if any) shell scripts in the future.
> 
> The only change I would request is that we need to fork https://github.com/ludeeus/action-shellcheck in a github.com/Seagate repository and reference it in the `uses` path that way, instead of directly referencing the remote repository to run code in our pipeline unsupervised.

Sure, let me address the same with. https://github.com/Seagate/action-shellcheck

2022-02-01 04:50 UTC, mukul-seagate11 commented
> @johnbent Thanks for that info. A couple of questions:
> 
> 1. The version of Shellcheck being used is quite old, can it be upgraded? There are a couple of style checks that I've enabled that are not supported in the Codacy version.
> 2. Looks like the Codacy run is not flagging the same number of issues, the issue counts are significantly less than what the manual run sees. Can we enable all of the checks (and reduce if needed)? Do you know how the config file setting works? Will it select the `.shellcheckrc` file if it's in the repository, that way it could be managed w/o access to the Codacy admin panel.
> 3. How do we get Codacy to fail the PR check if it detects these issues in the future?

Unfortunately, at the moment Codacy does not support configuration files for Shellcheck but yes can be addressed via github actions for Shellcheck

2022-02-01 06:09 UTC, mukul-seagate11 commented
Shellcheck workflow has been addressed via https://github.com/Seagate/cortx-k8s/pull/71

2022-02-01 18:56 UTC, osowski approved these changes
lgtm

2022-02-01 18:56 UTC, merged